spring:
  application:
    name: eureka-server
# Zipkin distributed tracing.
  zipkin:
    base-url: http://localhost:9411
# Server port
server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false