# Spring Boot configuration
spring:
  #profiles:
    #active: development
  application:
    name: customer
  # Database
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/customer
    username: 'postgres'
    password: 'postgres'
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Server configuration
server:
  port: 8080 #set your port